export enum Permission {
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_READ_ALL = 'USER_READ_ALL',
  USER_READ_ONE = 'USER_READ_ONE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Article Management
  ARTICLE_CREATE = 'ARTICLE_CREATE',
  ARTICLE_READ_ALL = 'ARTICLE_READ_ALL',
  ARTICLE_READ_ONE = 'ARTICLE_READ_ONE',
  ARTICLE_UPDATE_OWN = 'ARTICLE_UPDATE_OWN',
  ARTICLE_UPDATE_ANY = 'ARTICLE_UPDATE_ANY',
  ARTICLE_DELETE_OWN = 'ARTICLE_DELETE_OWN',
  ARTICLE_DELETE_ANY = 'ARTICLE_DELETE_ANY',

  // General Settings
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_EDIT = 'SETTINGS_EDIT',

  // Task Management
  TASK_CREATE = 'TASK_CREATE',
  TASK_READ_OWN_LIST = 'TASK_READ_OWN_LIST',
  TASK_READ_ANY_LIST = 'TASK_READ_ANY_LIST',
  TASK_READ_OWN_DETAIL = 'TASK_READ_OWN_DETAIL',
  TASK_READ_ANY_DETAIL = 'TASK_READ_ANY_DETAIL',
  TASK_UPDATE_OWN = 'TASK_UPDATE_OWN',
  TASK_UPDATE_ANY = 'TASK_UPDATE_ANY',
  TASK_DELETE_OWN = 'TASK_DELETE_OWN',
  TASK_DELETE_ANY = 'TASK_DELETE_ANY',
}
